name: mtrust_urp_usb_strategy
version: 9.0.0-11
environment: 
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.17.0'
description: USB Connection Strategy for URP
dependencies: 
  flutter: 
    sdk: flutter
  mtrust_urp_core: 
    path: ../mtrust_urp_core
  flutter_libserialport: ^0.4.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
repository: https://github.com/emdgroup/mtrust-urp
flutter: 
  uses-material-design: false
publish_to: none
