name: mtrust_urp_core
version: 8.0.2-2
environment: 
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.17.0'
description: Software SDK for interface with URP Devices
dependencies: 
  flutter: 
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_svg: ^2.0.10+1
  logger: ^2.3.0
  mtrust_urp_types: ^4.1.0
  protobuf: ^3.1.0
  shared_preferences: ^2.2.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  very_good_analysis: ^5.0.0+1
repository: https://github.com/emdgroup/mtrust-urp
flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
