name: Validate Dart
description: Validate Dart by running static analysis and tests

inputs:
  directory:
    description: "Directory where the Flutter project is located."
    required: true
  is_package:
    description: "Whether this project is a package or not. Will try to dry run the publish command if true."
    required: false
    default: "false"
  fatal_warnings:
    description: "Whether warnings are treated as fatal or not. Default is false."
    required: false
    default: "false"
  analyze_flags:
    description: "Additional flags to pass to flutter analyze. Default is '--no-fatal-warnings'."
    required: false
    default: "--fatal-warnings"

runs:
  using: "composite"
  steps:
    - name: Run static analysis
      run: |
        cd ${{ inputs.directory }}
        flutter analyze ${{ inputs.analyze_flags }}
      shell: bash

    - name: Run tests
      run: |
        cd ${{ inputs.directory }}
        flutter test
      shell: bash

    - name: Dry run publish package
      if: ${{ inputs.is_package == true }}
      run: |
        cd ${{ inputs.directory }}
        dart pub publish --dry-run
      shell: bash
