name: mtrust_urp_wifi_strategy
version: 9.0.0-13
environment: 
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.17.0'
description: WiFi Connection Strategy for URP
dependencies: 
  flutter: 
    sdk: flutter
  web_socket_channel: ^2.2.0
  mtrust_urp_core: ^9.0.0-13
dev_dependencies: 
  flutter_test: 
    sdk: flutter
repository: https://github.com/emdgroup/mtrust-urp
flutter: 
  uses-material-design: false
