name: mtrust_urp_virtual_strategy
version: 9.0.1
environment: 
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.17.0'
description: Virtual Connection Strategy for URP
dependencies: 
  flutter: 
    sdk: flutter
  freezed_annotation: ^2.0.3
  provider: ^6.0.2
  mtrust_urp_core: ^9.0.1
  json_annotation: ^4.8.1
  collection: ^1.18.0
  async: ^2.11.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
repository: https://github.com/emdgroup/mtrust-urp
flutter: 
  uses-material-design: false
