name: example
version: 9.1.0-13
publish_to: none
resolution: workspace
environment:
  sdk: ^3.6.0
  flutter: '>=1.17.0'
description: Example app for mtrust_urp_ui
dependencies: 
  flutter: 
    sdk: flutter
  liquid_flutter: ^23.0.0-2
  mtrust_urp_core:
    path: ../../packages/mtrust_urp_core
  mtrust_urp_ui:
    path: ../../packages/mtrust_urp_ui
  mtrust_urp_virtual_strategy:
    path: ../../packages/mtrust_urp_virtual_strategy
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^6.0.0
flutter: 
  uses-material-design: true
