name: mtrust_urp_ui
version: 9.0.1
environment: 
  sdk: ^3.5.0
  flutter: '>=1.17.0'
description: UI components for URP
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  mtrust_urp_types: ^6.2.0
  mtrust_urp_core: ^9.0.1
  intl: ^0.19.0
  liquid_flutter: ^22.0.1
  shared_preferences: ^2.3.5
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^4.0.0
  mtrust_urp_virtual_strategy: ^9.0.1
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.4
repository: https://github.com/emdgroup/mtrust-urp
flutter: 
  uses-material-design: true
  generate: true
  assets: 
    - assets/sec_reader.png
    - assets/imp_reader.png
    - assets/sec_led.png
