name: Publish package to pub.dev
description: Publish package to pub.dev
inputs:
  directory:
    description: "Directory"
    default: "."
  publish_mode:
    description: "Publish mode: --dry-run or --force"
    default: "--dry-run" # Default to --dry-run for safety

runs:
  using: composite
  steps:
    # Generate OIDC token for pub.dev
    - name: Generate OIDC token
      uses: dart-lang/setup-dart@v1

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.32.1"
    
    - name: Prepare Flutter for mtrust_urp_core 
      # We commit to prevent a warning while publishing of uncommitted changes
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "gh-actions@emdgroup.com"
        dart pub get
        dart run packages.dart set-deps --source=hosted
        
    - name: Push to pub.dev
      run: |
        cd ${{ inputs.directory }}
        dart pub publish ${{ inputs.publish_mode }}
      shell: bash
