name: "Prepare flutter runner"
description: "Prepares a flutter project by installing dependencies and running build_runner"
inputs:
  flutter_version:
    description: "Flutter version to be used"
    default: "3.41.2"
  artifactory_key:
    description: "Artifactory key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "${{ inputs.flutter_version }}"

    - name: 📦 Install dependencies
      shell: bash
      run: |
        dart pub get 
        dart run packages.dart set-deps --source=local
        dart run packages.dart install
        dart run packages.dart intl
