name: "Prepare flutter runner"
description: "Prepares a flutter project by installing dependencies and running build_runner"
inputs:
  directory:
    description: "Directory"
    required: true
    default: "."

  artifactory_key:
    description: "Artifactory key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.24.3"
    - name: 📦 Install dependencies
      shell: bash
      run: |
        dart pub get 
        dart run packages.dart set-deps --source=local
        dart run packages.dart install
