name: example
version: 9.1.0-2
environment: 
  sdk: ^3.5.0
  flutter: '>=1.17.0'
description: Example app for mtrust_urp_ui
dependencies: 
  flutter: 
    sdk: flutter
  liquid_flutter: ^22.0.1
  mtrust_urp_core: ^9.1.0-2
  mtrust_urp_ui: ^9.1.0-2
  mtrust_urp_virtual_strategy: ^9.1.0-2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: 
  uses-material-design: true
