on:
  workflow_call:
jobs:
  validate:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 🎯 Prepare Flutter
        uses: ./.github/actions/prepare-flutter

      - name: 👨🏻‍⚖️ Check dependency licenses
        run: |
          dart pub global activate very_good_cli
          dart run melos run check-licenses

      - name: 🔍 Analyze dart
        run: |
          dart run melos run analyze

      - name: 🧪 Run tests
        id: test
        run: |
          dart run melos run test

      - name: Upload test failures if tests fail
        uses: actions/upload-artifact@v4
        if: always() && steps.test.conclusion == 'failure'
        with:
          name: Golden test failures
          path: packages/mtrust_urp_ui/test/failures
